apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chronos.fullname" . }}
  labels:
    {{- include "chronos.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "chronos.selectorLabels" . | nindent 6 }}
