# Funding options for Chronos
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# Uncomment and configure the platforms you want to use:
# github: [username]
# patreon: username
# open_collective: chronos
# ko_fi: username
# custom: ["https://example.com/donate"]
