apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: policies.chronos.io
  annotations:
    crossplane.io/external-name: chronos-policy
spec:
  group: chronos.io
  names:
    kind: Policy
    listKind: PolicyList
    plural: policies
    singular: policy
    shortNames:
      - cpol
    categories:
      - chronos
      - crossplane
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Type
          type: string
          jsonPath: .spec.forProvider.type
        - name: Priority
          type: integer
          jsonPath: .spec.forProvider.priority
        - name: Enabled
          type: boolean
          jsonPath: .spec.forProvider.enabled
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - forProvider
              properties:
                forProvider:
                  type: object
                  required:
                    - name
                    - type
                  properties:
                    name:
                      type: string
                      description: Name of the policy
                    description:
                      type: string
                      description: Description of the policy
                    type:
                      type: string
                      enum: [scheduling, resource, security, compliance]
                      description: Type of policy
                    namespace:
                      type: string
                      description: Chronos namespace (empty for global)
                    enabled:
                      type: boolean
                      default: true
                    priority:
                      type: integer
                      minimum: 0
                      maximum: 1000
                      default: 100
                      description: Policy priority (higher = more important)
                    rules:
                      type: array
                      description: Policy matching rules
                      items:
                        type: object
                        required:
                          - field
                          - operator
                          - value
                        properties:
                          field:
                            type: string
                            description: Field to match (e.g., labels.team, job.name)
                          operator:
                            type: string
                            enum: [eq, ne, in, not_in, matches, gt, lt, gte, lte, exists, not_exists]
                          value:
                            type: string
                            description: Value to compare
                          values:
                            type: array
                            items:
                              type: string
                            description: Values for in/not_in operators
                    actions:
                      type: array
                      description: Actions when policy matches
                      items:
                        type: object
                        required:
                          - type
                        properties:
                          type:
                            type: string
                            enum: [set_label, add_annotation, set_timeout, add_resource, limit_resource, notify, block, allow, require_approval]
                          config:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            description: Action configuration
                    schedule:
                      type: object
                      description: Schedule constraints
                      properties:
                        allowedHours:
                          type: array
                          items:
                            type: integer
                            minimum: 0
                            maximum: 23
                        allowedDays:
                          type: array
                          items:
                            type: string
                            enum: [monday, tuesday, wednesday, thursday, friday, saturday, sunday]
                        timezone:
                          type: string
                          default: UTC
                        blackoutPeriods:
                          type: array
                          items:
                            type: object
                            properties:
                              start:
                                type: string
                                format: date-time
                              end:
                                type: string
                                format: date-time
                              reason:
                                type: string
                    resourceLimits:
                      type: object
                      description: Resource limits
                      properties:
                        maxConcurrentJobs:
                          type: integer
                        maxJobDuration:
                          type: string
                        maxRetries:
                          type: integer
                        maxCpuPerJob:
                          type: string
                        maxMemoryPerJob:
                          type: string
                providerConfigRef:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
            status:
              type: object
              properties:
                atProvider:
                  type: object
                  properties:
                    id:
                      type: string
                    matchedJobs:
                      type: integer
                    lastEvaluated:
                      type: string
                      format: date-time
                    violationCount:
                      type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
