name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear and concise description of what the problem is. Ex: I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Other approaches you've thought about.

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: What part of Chronos would this affect?
      options:
        - Scheduling / Cron
        - Job Execution / Dispatcher
        - API
        - Web UI
        - CLI (chronosctl)
        - Configuration
        - Metrics / Monitoring
        - Clustering / Raft
        - Storage
        - Documentation
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (to you)
      description: How important is this feature for your use case?
      options:
        - Nice to have
        - Important
        - Critical / Blocking

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
